In [0]:

import pandas as pd
import numpy as np
dataset_train = pd.read_csv('train.csv')
dataset_train.head()

Severity  ...  Accident_ID
0                Minor_Damage_And_Injuries  ...         7570
1                Minor_Damage_And_Injuries  ...        12128
2        Significant_Damage_And_Fatalities  ...         2181
3  Significant_Damage_And_Serious_Injuries  ...         5946
4        Significant_Damage_And_Fatalities  ...         9054

[5 rows x 12 columns]

In [0]:
x = dataset_train.drop(['Severity'] , axis = 1)
y= dataset_train['Severity']
x=x.drop(['Accident_ID'],axis=1)

In [0]:
x.head()

Safety_Score  Days_Since_Inspection  ...  Violations  Adverse_Weather_Metric
0     49.223744                     14  ...           3                0.424352
1     62.465753                     10  ...           2                0.352350
2     63.059361                     13  ...           3                0.003364
3     48.082192                     11  ...           1                0.211728
4     26.484018                     13  ...           2                0.176883

[5 rows x 10 columns]

In [0]:
y

0                     Minor_Damage_And_Injuries
1                     Minor_Damage_And_Injuries
2             Significant_Damage_And_Fatalities
3       Significant_Damage_And_Serious_Injuries
4             Significant_Damage_And_Fatalities
                         ...                   
9995    Significant_Damage_And_Serious_Injuries
9996                  Highly_Fatal_And_Damaging
9997    Significant_Damage_And_Serious_Injuries
9998                  Minor_Damage_And_Injuries
9999                  Highly_Fatal_And_Damaging
Name: Severity, Length: 10000, dtype: object

In [0]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
y


array([1, 1, 2, ..., 3, 1, 0])

In [0]:
x

Safety_Score  Days_Since_Inspection  ...  Violations  Adverse_Weather_Metric
0        49.223744                     14  ...           3                0.424352
1        62.465753                     10  ...           2                0.352350
2        63.059361                     13  ...           3                0.003364
3        48.082192                     11  ...           1                0.211728
4        26.484018                     13  ...           2                0.176883
...            ...                    ...  ...         ...                     ...
9995     56.118721                      8  ...           2                0.026150
9996     40.365297                     10  ...           2                0.074898
9997     27.853881                     17  ...           3                0.168173
9998     56.210046                      8  ...           2                0.026381
9999     50.000000                     13  ...           2                0.017036

[10000 rows x 10 columns]

In [0]:
from sklearn.model_selection import train_test_split
x , x_test , y , y_test = train_test_split(x, y , test_size = 0.15 , random_state=0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x = sc_x.fit_transform(x)
x_test  = sc_x.transform(x_test)

In [0]:
#TRAINING




In [0]:
import tensorflow as tf

from keras import Sequential
from keras.layers import Dense

In [0]:
classifier=Sequential()

In [0]:
classifier = tf.keras.Sequential([
    tf.keras.layers.Dense(500 , activation = 'relu' , input_dim = 10),
    tf.keras.layers.Dense(300 , activation = 'relu'),
    tf.keras.layers.Dense(100 , activation = 'relu'),
    tf.keras.layers.Dense(50 , activation = 'relu'),
    tf.keras.layers.Dense(4, activation = 'softmax')
])

In [0]:
classifier.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_30 (Dense)             (None, 500)               5500      
_________________________________________________________________
dense_31 (Dense)             (None, 300)               150300    
_________________________________________________________________
dense_32 (Dense)             (None, 100)               30100     
_________________________________________________________________
dense_33 (Dense)             (None, 50)                5050      
_________________________________________________________________
dense_34 (Dense)             (None, 4)                 204       
Total params: 191,154
Trainable params: 191,154
Non-trainable params: 0
_________________________________________________________________


In [0]:
classifier.compile(loss = 'sparse_categorical_crossentropy',
                 optimizer = 'adam',
                 metrics = ['accuracy'])

In [0]:
classifier.fit(x , y, batch_size = 16, epochs = 50 )


Train on 8500 samples
Epoch 1/50
8500/8500 [==============================] - 1s 161us/sample - loss: 0.5048 - acc: 0.8081
Epoch 2/50
8500/8500 [==============================] - 1s 139us/sample - loss: 0.2565 - acc: 0.9140
Epoch 3/50
8500/8500 [==============================] - 1s 153us/sample - loss: 0.2211 - acc: 0.9242
Epoch 4/50
8500/8500 [==============================] - 1s 139us/sample - loss: 0.2100 - acc: 0.9299
Epoch 5/50
8500/8500 [==============================] - 1s 141us/sample - loss: 0.2013 - acc: 0.9319
Epoch 6/50
8500/8500 [==============================] - 1s 141us/sample - loss: 0.1818 - acc: 0.9399
Epoch 7/50
8500/8500 [==============================] - 1s 148us/sample - loss: 0.1745 - acc: 0.9420
Epoch 8/50
8500/8500 [==============================] - 1s 142us/sample - loss: 0.1762 - acc: 0.9414
Epoch 9/50
8500/8500 [==============================] - 1s 140us/sample - loss: 0.1646 - acc: 0.9448
Epoch 10/50
8500/8500 [==============================] - 1s 136us/sam

In [0]:
#TESTING DATA TO BE PREDICTED




In [0]:
test_dataset = pd.read_csv('test.csv')
test_x = test_dataset.drop(['Accident_ID'] , axis = 1)
test_x.head()

Safety_Score  Days_Since_Inspection  ...  Violations  Adverse_Weather_Metric
0     19.497717                     16  ...           2                0.069692
1     58.173516                     15  ...           2                0.002777
2     33.287671                     15  ...           1                0.004316
3      3.287671                     21  ...           2                0.199990
4     10.867580                     18  ...           2                0.483696

[5 rows x 10 columns]

In [0]:
#STANDARDISE DATA TO BE PREDICTED


#test_x to test_x1 

In [0]:
test_x1 = sc_x.transform(test_x)


In [0]:
test_x1

array([[-1.39038509,  0.86841631, -0.08055941, ...,  0.63469773,
        -0.01065125, -0.48425896],
       [ 1.01078336,  0.58511028, -0.51140359, ..., -0.1833038 ,
        -0.01065125, -0.6604276 ],
       [-0.53424239,  0.58511028, -0.51140359, ..., -1.51468037,
        -0.97379599, -0.65637585],
       ...,
       [-0.32162417,  0.30180425,  0.49389949, ...,  0.5003538 ,
        -0.01065125, -0.64502209],
       [-0.19688814,  0.01849822,  1.06835839, ..., -0.81444749,
        -0.97379599, -0.65129438],
       [-0.3613129 , -0.54811384, -0.79863304, ...,  0.4206145 ,
        -1.93694072, -0.60347751]])

In [0]:
pred2=classifier.predict(test_x1)
pred2


array([[1.0000000e+00, 1.3801080e-09, 3.6291543e-11, 9.5181969e-09],
       [8.9960333e-09, 3.9875178e-07, 9.9999952e-01, 1.6707283e-07],
       [3.0713153e-07, 1.5760388e-05, 1.5080886e-13, 9.9998391e-01],
       ...,
       [7.4732881e-08, 1.0854888e-09, 6.2045381e-19, 9.9999988e-01],
       [5.1165031e-11, 3.6032668e-12, 7.3738656e-26, 1.0000000e+00],
       [9.9980265e-01, 8.7990011e-05, 1.0065275e-05, 9.9301964e-05]],
      dtype=float32)

In [0]:
np.shape(pred2)


(2500, 4)

In [0]:
contents = []
for x in pred2:    
    contents.append(x.argmax())

In [0]:
d = {0 : 'Highly_Fatal_And_Damaging', 1 : 'Minor_Damage_And_Injuries', 2: 'Significant_Damage_And_Fatalities', 3:'Significant_Damage_And_Serious_Injuries'}

In [0]:
final_1 = []
for i in contents:
    final_1.append(d[i])

In [0]:
final_1

['Highly_Fatal_And_Damaging',
 'Significant_Damage_And_Fatalities',
 'Significant_Damage_And_Serious_Injuries',
 'Highly_Fatal_And_Damaging',
 'Highly_Fatal_And_Damaging',
 'Significant_Damage_And_Fatalities',
 'Significant_Damage_And_Fatalities',
 'Highly_Fatal_And_Damaging',
 'Highly_Fatal_And_Damaging',
 'Significant_Damage_And_Serious_Injuries',
 'Significant_Damage_And_Serious_Injuries',
 'Significant_Damage_And_Serious_Injuries',
 'Highly_Fatal_And_Damaging',
 'Significant_Damage_And_Serious_Injuries',
 'Significant_Damage_And_Fatalities',
 'Significant_Damage_And_Serious_Injuries',
 'Highly_Fatal_And_Damaging',
 'Significant_Damage_And_Serious_Injuries',
 'Minor_Damage_And_Injuries',
 'Significant_Damage_And_Fatalities',
 'Highly_Fatal_And_Damaging',
 'Significant_Damage_And_Serious_Injuries',
 'Highly_Fatal_And_Damaging',
 'Highly_Fatal_And_Damaging',
 'Highly_Fatal_And_Damaging',
 'Significant_Damage_And_Fatalities',
 'Highly_Fatal_And_Damaging',
 'Highly_Fatal_And_Damaging',


In [0]:
output = pd.DataFrame({'Accident_ID': test_dataset.Accident_ID, 'Severity': final_1})
output.to_csv('my_submission.csv', index=False)